import type { FishNetStatusDefinition } from "../catalog.ts";

/**
 * Hand-ported from the Spirit Vale data-mine's statuses.json. A status's own
 * duration is aggregated from every other status/skill definition that grants it,
 * since the raw data declares durations on the granter, not the granted status.
 * isDebuff also applies manual overrides on top of the source data, which only marks
 * 8/185 statuses as debuffs and misses obvious ones like Stun/Blind/Silence/Slow.
 */
export class StatusDefinitions {
  private constructor() {}

  static readonly values: readonly FishNetStatusDefinition[] = [
  { id: "Aegis", displayName: "Aegis", spriteId: "3-Aegis", isDebuff: false, maxLevel: 0, fixedDuration: true, effects: [] },
  { id: "Aggressive", displayName: "Aggressive", spriteId: "Conditions_Immune_12", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Agility", displayName: "Inner Focus", spriteId: "T_Icon_Gold_81", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Alacrity", displayName: "Alacrity", spriteId: "Conditions_32", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Anathema", displayName: "Anathema", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "AngelicBlessing", displayName: "Angelic Blessing", spriteId: "47-EnchantArmorHoly", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "ArcaneSigil", displayName: "Arcane Sigil", spriteId: "T_Icon_Energy_55", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "ArmorBreak", displayName: "Armor Break", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Armored", displayName: "Armored", spriteId: "Skills_247", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Barrier", displayName: "Sacred Aegis", spriteId: "16-barrier", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Berserk", displayName: "Berserk", spriteId: "Berserker11", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "BleedCoating", displayName: "Red Maw", spriteId: "Skills_339", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Bleeding", displayName: "Bleeding", spriteId: "Conditions_2", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [{ id: "BleedCoating", duration: 5, durationPerLevel: 1, chance: 0, chancePerLevel: 0, stacks: 0, stacksPerLevel: 0 }, { id: "BloodFrenzy", duration: 5, durationPerLevel: 0, chance: 0, chancePerLevel: 0, stacks: 0, stacksPerLevel: 0 }, { id: "Lockdown", duration: 5, durationPerLevel: 0, chance: 0, chancePerLevel: 0, stacks: 0, stacksPerLevel: 0 }] },
  { id: "Blessing", displayName: "Benediction", spriteId: "49-blessing", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Blind", displayName: "Blind", spriteId: "Conditions_3", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "BlindImmunity", displayName: "Blind Immunity", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "BloodCrash", displayName: "Blood Crash", spriteId: "T_Icon_BloodCombat_31", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "BloodFrenzy", displayName: "Blood Frenzy", spriteId: "Berserker16", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "BloodLust", displayName: "Blood Lust", spriteId: "T_Icon_BloodCombat_39", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Bloodprice", displayName: "Bloodprice", spriteId: "T_Icon_BloodCombat_13", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "BoostAxeArc", displayName: "Bloodtrail", spriteId: "Barbarian18", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "BoostAxeVortex", displayName: "Warmaw", spriteId: "Barbarian13", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "BoostBash", displayName: "Breakjaw", spriteId: "Barbarian20", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "BoostSmite", displayName: "Martyr's Oath", spriteId: "50-smite", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "BoostStomp", displayName: "Gorepath", spriteId: "Skills_593", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Burning", displayName: "Burning", spriteId: "Conditions_9", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "BurningImmunity", displayName: "Burning Immunity", spriteId: "Conditions_Immune_9", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "CastReady", displayName: "Cast Ready", spriteId: "Skills_556", isDebuff: false, maxLevel: 0, fixedDuration: true, effects: [] },
  { id: "Cloaking", displayName: "Cloaking", spriteId: "Skills_510", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "CombatMounted", displayName: "Combat Mounted", spriteId: "T_Icon_Nature_70", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "ComboReady", displayName: "Combo Ready", spriteId: "T_Icon_BloodCombat_16", isDebuff: false, maxLevel: 0, fixedDuration: true, effects: [] },
  { id: "Conjurer", displayName: "Conjurer", spriteId: "T_Icon_Arcane_21", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "CorpseBarrier", displayName: "Corpse Barrier", spriteId: "Necromancer15", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "CorpseExplosion", displayName: "Corpse Explosion", spriteId: "Necromancer14", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Counter", displayName: "Counter", spriteId: "Skills_331", isDebuff: false, maxLevel: 0, fixedDuration: true, effects: [] },
  { id: "Curse", displayName: "Curse", spriteId: "Conditions_33", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "CurseImmunity", displayName: "Curse Immunity", spriteId: "Conditions_Immune_33", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "DeathBond", displayName: "Death Bond", spriteId: "T_Icon_Shadow_88", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "DeathBramble", displayName: "Necrotic Presence", spriteId: "48-DeathBramble", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "DeathBrambleEnemy", displayName: "Necrotic Presence Enemy", spriteId: "48-DeathBramble", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Decay", displayName: "Decay", spriteId: "Conditions_5", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "DecayImmunity", displayName: "Decay Immunity", spriteId: "Conditions_Immune_5", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Defiance", displayName: "Defiance", spriteId: "Conditions_25", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Divinity", displayName: "Divinity", spriteId: "25-Divinity", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "EarthAttunement", displayName: "Earth Attunement", spriteId: "earth", isDebuff: false, maxLevel: 5, fixedDuration: false, effects: [] },
  { id: "EarthBarrier", displayName: "Earth Barrier", spriteId: "Geomancer5", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "EarthBarrier2", displayName: "Arcane Barrier", spriteId: "Geomancer5", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "EarthExposure", displayName: "Earth Exposure", spriteId: "earth", isDebuff: true, maxLevel: 5, fixedDuration: false, effects: [] },
  { id: "EclipsingAegis", displayName: "Eclipsing Aegis", spriteId: "42-barrier", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "ElementalAttunement", displayName: "Elemental Attunement", spriteId: "Enchanter20", isDebuff: false, maxLevel: 5, fixedDuration: false, effects: [] },
  { id: "Elusive", displayName: "Elusive", spriteId: "T_Icon_Unholy_63", isDebuff: false, maxLevel: 0, fixedDuration: true, effects: [] },
  { id: "EnchantArmorHoly", displayName: "Sanctify", spriteId: "47-EnchantArmorHoly", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "EnchantEarth", displayName: "Enchant Earth", spriteId: "Skills_584", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "EnchantFire", displayName: "Enchant Fire", spriteId: "T_Icon_Fire_80", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "EnchantHoly", displayName: "Enchant Holy", spriteId: "22-endowholy", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "EnchantPoison", displayName: "Enchant Poison", spriteId: "Skills_497", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "EnchantShadow", displayName: "Enchant Shadow", spriteId: "Skills_514", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "EnchantUndead", displayName: "Enchant Undead", spriteId: "T_Icon_Shadow_77", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "EnchantWater", displayName: "Enchant Water", spriteId: "T_Icon_Energy_43", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "EnchantWind", displayName: "Enchant Wind", spriteId: "Skills_379", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Endure", displayName: "Endure", spriteId: "T_Icon_Energy_72", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "EnergyShield", displayName: "Energy Shield", spriteId: "Skills_362", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Enrage", displayName: "Enrage", spriteId: "Berserker18", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "ExorcistBrand", displayName: "Exorcist's Brand", spriteId: "14-exorcism", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Fanaticism", displayName: "Fanaticism", spriteId: "T_Icon_Fire_104", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Ferocity", displayName: "Ferocity", spriteId: "T_Icon_BloodCombat_89", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "FireAttunement", displayName: "Fire Attunement", spriteId: "fire", isDebuff: false, maxLevel: 5, fixedDuration: false, effects: [] },
  { id: "FireBarrier", displayName: "Fire Barrier", spriteId: "Pyromancer16", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "FireBarrier2", displayName: "Arcane Barrier", spriteId: "Pyromancer16", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "FireExposure", displayName: "Fire Exposure", spriteId: "fire", isDebuff: true, maxLevel: 5, fixedDuration: false, effects: [] },
  { id: "FireRelease", displayName: "Fire Release", spriteId: "Skills_052", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Flow", displayName: "Flow", spriteId: "22-scout-flow", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "FlowState", displayName: "Flow State", spriteId: "Skills_570", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Focus", displayName: "Focus", spriteId: "Conditions_0", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "FreezingEdge", displayName: "Frost Rounds", spriteId: "sf_s_085", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Frenzy", displayName: "Frenzy", spriteId: "Conditions_11", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Frozen", displayName: "Frozen", spriteId: "Conditions_10", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [{ id: "FreezingEdge", duration: 5, durationPerLevel: 1, chance: 0.3, chancePerLevel: 0, stacks: 0, stacksPerLevel: 0 }] },
  { id: "FrozenImmunity", displayName: "Frozen Immunity", spriteId: "Conditions_Immune_10", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Fury", displayName: "Fury", spriteId: "Conditions_12", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "FuryBond", displayName: "Fury Bond", spriteId: "T_Icon_Fire_132", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "GameMasterCloaking", displayName: "Game Master Cloaking", spriteId: "Skills_510", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "GospelOfGrace", displayName: "Gospel Of Grace", spriteId: "49-HolyLight", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Grace", displayName: "Divine Grace", spriteId: "34-grace", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "GraveChill", displayName: "Grave Chill", spriteId: "Necromancer3", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "GraveChillEnemy", displayName: "Grave Chill Enemy", spriteId: "Necromancer3", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "GuardianBond", displayName: "Guardian Bond", spriteId: "T_Icon_Unholy_04", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "GuardianSpirit", displayName: "Guardian Spirit", spriteId: "49-HolyLight", isDebuff: false, maxLevel: 0, fixedDuration: true, effects: [] },
  { id: "Haste", displayName: "Haste", spriteId: "Conditions_14", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "HighGuard", displayName: "High Guard", spriteId: "29-HighGuard", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "HolyAttunement", displayName: "Holy Attunement", spriteId: "holy", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "HolyExposure", displayName: "Consecrated", spriteId: "holy", isDebuff: true, maxLevel: 5, fixedDuration: false, effects: [] },
  { id: "HolyShield", displayName: "Holy Shield", spriteId: "33-HolyShield", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "HonedTechnique", displayName: "Honed Technique", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "IceRelease", displayName: "Ice Release", spriteId: "Skills_137", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Invoker", displayName: "Invoker", spriteId: "T_Icon_Arcane_26", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "IronResponse", displayName: "Iron Response", spriteId: "Skills_301", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "LauncherBoost", displayName: "Launcher Boost", spriteId: "sf_s_095", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "LauncherPoison", displayName: "Launcher Poison", spriteId: "151", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "LifeBond", displayName: "Life Bond", spriteId: "38-LifeBond", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "LightningCoat", displayName: "Lightning Coat", spriteId: "Skills_366", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "LightningReflexes", displayName: "Lightning Reflexes", spriteId: "Skills_397", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "LightningRelease", displayName: "Lightning Release", spriteId: "Skills_355", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "LimitBreak", displayName: "Limit Break", spriteId: "T_Icon_Shadow_44", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Lockdown", displayName: "Lockdown", spriteId: "T_Icon_BloodCombat_06", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "MagicExposure", displayName: "Magic Exposure", spriteId: "Conditions_28", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "ManaEcho", displayName: "Mana Echo", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Marked", displayName: "Marked", spriteId: "T_Icon_BloodCombat_11", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Might", displayName: "Might", spriteId: "Conditions_18", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "MindBreak", displayName: "Mind Break", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Mounted", displayName: "Mounted", spriteId: "T_Icon_Gold_64", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Multistrike", displayName: "Multistrike", spriteId: "Skills_307", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "NPC_Berserk", displayName: "NPC- Berserk", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "NPC_Enrage", displayName: "Enrage", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "NPC_Enrage_2", displayName: "Last Stand", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "NPC_LightningReflexes", displayName: "NPC- Lightning Reflexes", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "NPC_Sharpen", displayName: "NPC- Sharpen", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "NPC_SpellGuard", displayName: "NPC- Spell Guard", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "NPC_SpikedShell", displayName: "NPC- Spiked Shell", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "NPC_SteelGuard", displayName: "NPC- Steel Guard", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "PerfectStrike", displayName: "Perfect Strike", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "PistolBoost", displayName: "Pistol Boost", spriteId: "T_Icon_BloodCombat_04", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Poison", displayName: "Poison", spriteId: "Conditions_20", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [{ id: "LauncherPoison", duration: 5, durationPerLevel: 0, chance: 0, chancePerLevel: 0, stacks: 0, stacksPerLevel: 0 }, { id: "VenomCoating", duration: 5, durationPerLevel: 1, chance: 0, chancePerLevel: 0, stacks: 0, stacksPerLevel: 0 }] },
  { id: "PoisonExposure", displayName: "Poison Exposure", spriteId: "poison", isDebuff: true, maxLevel: 5, fixedDuration: false, effects: [] },
  { id: "PoisonImmunity", displayName: "Poison Immunity", spriteId: "Conditions_Immune_20", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Protection", displayName: "Protection", spriteId: "Conditions_21", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Radiance", displayName: "Radiance", spriteId: "Priest11", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "RadiantBulwark", displayName: "Radiant Bulwark", spriteId: "Priest12", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Rage", displayName: "Rage", spriteId: "Berserker18", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [{ id: "Enrage", duration: 5, durationPerLevel: 0, chance: 1, chancePerLevel: 0, stacks: 0, stacksPerLevel: 0 }] },
  { id: "Regeneration", displayName: "Regeneration", spriteId: "Conditions_23", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Revealed", displayName: "Revealed", spriteId: "Conditions_3", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "RifleBoost", displayName: "Rifle Boost", spriteId: "T_Icon_Gold_89", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Ruthless", displayName: "Ruthless", spriteId: "Skills_306", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Sacrament", displayName: "Sacrament", spriteId: "T_Icon_Energy_93", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "SacredGround", displayName: "Sacred Ground", spriteId: "Priest12", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Sacrifice", displayName: "Sacrifice", spriteId: "48-Sacrifice", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Sanctuary", displayName: "Sanctuary", spriteId: "24-sanctuary", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Sanctuary2", displayName: "Sanctuary Doctrine", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "ShadowMark", displayName: "Shadow Mark", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "ShockAbsorber", displayName: "Shock Absorber", spriteId: "sf_s_074", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "ShotgunBoost", displayName: "Shotgun Boost", spriteId: "T_Icon_Frost_03", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Silence", displayName: "Silence", spriteId: "Conditions_26", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "SilenceImmunity", displayName: "Silence Immunity", spriteId: "Conditions_Immune_26", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "SilentEdge", displayName: "Silent Edge", spriteId: "T_Icon_Arcane_37", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Sitting", displayName: "Sitting", spriteId: "Skills_418", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Slow", displayName: "Slow", spriteId: "Conditions_27", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "SlowImmunity", displayName: "Slow Immunity", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "SmokeScreen", displayName: "Smoke Screen", spriteId: "Skills_515", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "SniperNest", displayName: "Sniper Nest", spriteId: "T_Icon_Nature_132", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "SoulDrain", displayName: "Soul Drain", spriteId: "T_Icon_Unholy_151", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "SoulDrainEnemy", displayName: "Soul Drain Enemy", spriteId: "T_Icon_Unholy_151", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "SpearQuicken", displayName: "Spear Quicken", spriteId: "Skills_534", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "SpellShield", displayName: "Arcanum Ward", spriteId: "T_Icon_Energy_35", isDebuff: false, maxLevel: 0, fixedDuration: true, effects: [] },
  { id: "Spinning", displayName: "Spinning", spriteId: "Skills_565", isDebuff: false, maxLevel: 0, fixedDuration: true, effects: [] },
  { id: "SpiritBond", displayName: "Spirit Bond", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Stability", displayName: "Stability", spriteId: "Conditions_35", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Stagger", displayName: "Stagger", spriteId: "Conditions_7", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Stamina", displayName: "Stamina", spriteId: "Conditions_17", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Stun", displayName: "Stun", spriteId: "Conditions_31", isDebuff: true, maxLevel: 0, fixedDuration: true, effects: [] },
  { id: "StunImmunity", displayName: "Stun Immunity", spriteId: "Conditions_Immune_31", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "SummonSpeed", displayName: "Summon Speed", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Taunt", displayName: "Taunt", spriteId: "13-taunt", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "TempestEngine", displayName: "Tempest Engine", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "TriggerHappy", displayName: "Trigger Happy", spriteId: "T_Icon_BloodCombat_10", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "TwohandQuicken", displayName: "Axe Quicken", spriteId: "Skills_380", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "UmbralCurse", displayName: "Umbral Curse", spriteId: "T_Icon_Shadow_04", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "UmbralMark", displayName: "Umbral Mark", spriteId: "T_Icon_Shadow_63", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "UndeadExposure", displayName: "Desecrated", spriteId: "undead", isDebuff: true, maxLevel: 5, fixedDuration: false, effects: [] },
  { id: "UnholyAura", displayName: "Unholy Aura", spriteId: "T_Icon_Unholy_148", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "UnholyFrenzy", displayName: "Unholy Frenzy", spriteId: "T_Icon_BloodCombat_50", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Unyielding", displayName: "Unyielding", spriteId: "Berserker8", isDebuff: false, maxLevel: 0, fixedDuration: true, effects: [] },
  { id: "VenomCoating", displayName: "Venom Coating", spriteId: "T_Icon_Unholy_02", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "VenomStep", displayName: "Venom Step", spriteId: "Skills_499", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Vitality", displayName: "Vitality", spriteId: "Conditions_15", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Volatile", displayName: "Volatile", spriteId: "T_Icon_Arcane_63", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "Vulnerability", displayName: "Vulnerability", spriteId: "Conditions_4", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "WaterAttunement", displayName: "Water Attunement", spriteId: "water", isDebuff: false, maxLevel: 5, fixedDuration: false, effects: [] },
  { id: "WaterBarrier", displayName: "Water Barrier", spriteId: "Skills_117", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "WaterBarrier2", displayName: "Arcane Barrier", spriteId: "Skills_117", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "WaterExposure", displayName: "Water Exposure", spriteId: "water", isDebuff: true, maxLevel: 5, fixedDuration: false, effects: [] },
  { id: "Weaken", displayName: "Weaken", spriteId: "Conditions_22", isDebuff: true, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "WindAttunement", displayName: "Wind Attunement", spriteId: "wind", isDebuff: false, maxLevel: 5, fixedDuration: false, effects: [] },
  { id: "WindBarrier", displayName: "Wind Barrier", spriteId: "Skills_356", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "WindBarrier2", displayName: "Arcane Barrier", spriteId: "Skills_356", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  { id: "WindExposure", displayName: "Wind Exposure", spriteId: "wind", isDebuff: true, maxLevel: 5, fixedDuration: false, effects: [] },
  { id: "Zeal", displayName: "Zeal", spriteId: "T_Icon_Gold_92", isDebuff: false, maxLevel: 0, fixedDuration: false, effects: [] },
  ];
}
