#!/usr/bin/env bun
/** Generates build-scoped combat capability sets from data-mine skill/status JSON exports. */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const skillsPath = process.argv[2];
const statusesPath = process.argv[3];
const rpcBuildPath = process.argv[4];
if (!skillsPath || !statusesPath || !rpcBuildPath) {
  throw new Error("Usage: bun run scripts/generate-combat-semantics.ts <skills.json> <statuses.json> <rpc-build.json>");
}
for (const input of [skillsPath, statusesPath, rpcBuildPath]) {
  if (!existsSync(input)) throw new Error(`input not found: ${input}`);
}

type Effect = { Id?: string };
type Skill = {
  id: string;
  kinds?: string[];
  config?: {
    Damage?: { Value?: number; ValueLv?: number };
    StatusEffects?: Effect[];
    SelfStatusEffects?: Effect[];
  };
};
type Status = { id: string; config?: { Passives?: { Type?: number }[] } };

const skills = JSON.parse(readFileSync(skillsPath, "utf8")) as Skill[];
const statuses = JSON.parse(readFileSync(statusesPath, "utf8")) as Status[];
const rpcBuild = JSON.parse(readFileSync(rpcBuildPath, "utf8")) as { wireMap?: { buildFingerprint?: string } };
const buildFingerprint = rpcBuild.wireMap?.buildFingerprint;
if (!buildFingerprint) throw new Error("rpc-build.json is missing wireMap.buildFingerprint");
const barrierStatusIds = statuses
  .filter(({ config }) => config?.Passives?.some(({ Type }) => Type === 118))
  .map(({ id }) => id)
  .sort();
const barrierStatuses = new Set(barrierStatusIds);
const statusIds = (skill: Skill) => [
  ...(skill.config?.StatusEffects ?? []),
  ...(skill.config?.SelfStatusEffects ?? []),
].flatMap(({ Id }) => Id ? [Id] : []);
const activeSkills = skills.filter(({ kinds }) => kinds?.includes("active"));
const regenerationSkillIds = activeSkills
  .filter((skill) => statusIds(skill).includes("Regeneration"))
  .map(({ id }) => id)
  .sort();
const directHealingSkillIds = activeSkills
  .filter((skill) => {
    const damage = skill.config?.Damage;
    return ((damage?.Value ?? 0) < 0 || (damage?.ValueLv ?? 0) < 0)
      && !statusIds(skill).includes("Regeneration");
  })
  .map(({ id }) => id)
  .sort();
const barrierSkillIds = activeSkills
  .filter((skill) => statusIds(skill).some((id) => barrierStatuses.has(id)))
  .map(({ id }) => id)
  .sort();

const output = `/** AUTO-GENERATED by scripts/generate-combat-semantics.ts. Do not hand-edit. */
export const COMBAT_SEMANTICS_BUILD_FINGERPRINT = ${JSON.stringify(buildFingerprint)};
export const DIRECT_HEALING_SKILL_IDS = new Set(${JSON.stringify(directHealingSkillIds, null, 2)});
export const REGENERATION_SKILL_IDS = new Set(${JSON.stringify(regenerationSkillIds, null, 2)});
export const BARRIER_SKILL_IDS = new Set(${JSON.stringify(barrierSkillIds, null, 2)});
export const BARRIER_STATUS_IDS = new Set(${JSON.stringify(barrierStatusIds, null, 2)});
`;
const outputPath = path.resolve(import.meta.dir, "../packages/combat/src/generated/combat-semantics.ts");
mkdirSync(path.dirname(outputPath), { recursive: true });
writeFileSync(outputPath, output, "utf8");
console.log(`Generated combat semantics: ${directHealingSkillIds.length} direct heals, ${regenerationSkillIds.length} regeneration skills, ${barrierSkillIds.length} barrier skills.`);
