import { readFileSync } from "node:fs";
import type { ElectrobunConfig } from "electrobun";

interface PackageJson {
  version?: string;
}

const packageJson = JSON.parse(
  readFileSync(new URL("../../package.json", import.meta.url), "utf8"),
) as PackageJson;
if (!packageJson.version) throw new Error("package.json must define a version before building Electrobun.");

/**
 * Electrobun's `copy` config is a plain `{ [sourcePath]: destPath }` map, so copying the
 * same `theme.css` into every view's own folder needs a textually distinct source key per
 * view even though every one resolves to the same file — otherwise the object literal would
 * silently collapse duplicate keys and most views would end up without a theme.css.
 */
function themeCssSource(variant: number): string {
  return `../ui-core/${"./".repeat(variant)}theme.css`;
}

export default {
  app: {
    name: "Spirit Vale",
    identifier: "dev.spiritvale.desktop",
    version: packageJson.version,
    description: "Centralized capture and desktop tools for Spirit Vale.",
  },
  build: {
    bun: { entrypoint: "src/desktop/index.ts" },
    views: {
      launcherview: { entrypoint: "src/launcherview/index.ts" },
      settingsview: { entrypoint: "src/settingsview/index.ts" },
      mainview: { entrypoint: "../combat-ui/src/mainview/index.tsx" },
      overlayview: { entrypoint: "../overlay/src/overlayview/index.tsx" },
      overlaysettingsview: { entrypoint: "../overlay/src/overlaysettingsview/index.tsx" },
      characterview: { entrypoint: "src/characterview/index.ts" },
      marketview: { entrypoint: "../market-ui/src/marketview/index.tsx" },
      marketfiltersview: { entrypoint: "../market-ui/src/marketfiltersview/index.tsx" },
      rewardsview: { entrypoint: "../rewards-ui/src/rewardsview/index.tsx" },
      rewardscatalogview: { entrypoint: "../rewards-ui/src/catalogview/index.tsx" },
      sessionpickerview: { entrypoint: "src/sessionpickerview/index.ts" },
      analysisview: { entrypoint: "../combat-ui/src/analysisview/index.tsx" },
      analysisdetailview: { entrypoint: "../combat-ui/src/analysisdetailview/index.tsx" },
    },
    copy: {
      "../../static/icon/eggplant_icon_320px.png": "views/assets/app-icon.png",
      "../../static/icon/eggplant_icon.ico": "views/assets/app-icon.ico",
      "../../static/class_icons/class-acolyte.webp": "views/assets/class-icons/class-acolyte.webp",
      "../../static/class_icons/class-berserker.webp": "views/assets/class-icons/class-berserker.webp",
      "../../static/class_icons/class-gunslinger.webp": "views/assets/class-icons/class-gunslinger.webp",
      "../../static/class_icons/class-knight.webp": "views/assets/class-icons/class-knight.webp",
      "../../static/class_icons/class-mage.webp": "views/assets/class-icons/class-mage.webp",
      "../../static/class_icons/class-necromancer.webp": "views/assets/class-icons/class-necromancer.webp",
      "../../static/class_icons/class-paladin.webp": "views/assets/class-icons/class-paladin.webp",
      "../../static/class_icons/class-priest.webp": "views/assets/class-icons/class-priest.webp",
      "../../static/class_icons/class-rogue.webp": "views/assets/class-icons/class-rogue.webp",
      "../../static/class_icons/class-scout.webp": "views/assets/class-icons/class-scout.webp",
      "../../static/class_icons/class-shinobi.webp": "views/assets/class-icons/class-shinobi.webp",
      "../../static/class_icons/class-summoner.webp": "views/assets/class-icons/class-summoner.webp",
      "../../static/class_icons/class-warrior.webp": "views/assets/class-icons/class-warrior.webp",
      "../../static/class_icons/class-weaver.webp": "views/assets/class-icons/class-weaver.webp",
      "../../static/class_icons/class-wizard.webp": "views/assets/class-icons/class-wizard.webp",
      "../../static/status-icons/13-taunt.webp": "views/assets/status-icons/13-taunt.webp",
      "../../static/status-icons/14-exorcism.webp": "views/assets/status-icons/14-exorcism.webp",
      "../../static/status-icons/151.webp": "views/assets/status-icons/151.webp",
      "../../static/status-icons/16-barrier.webp": "views/assets/status-icons/16-barrier.webp",
      "../../static/status-icons/22-endowholy.webp": "views/assets/status-icons/22-endowholy.webp",
      "../../static/status-icons/22-scout-flow.webp": "views/assets/status-icons/22-scout-flow.webp",
      "../../static/status-icons/24-sanctuary.webp": "views/assets/status-icons/24-sanctuary.webp",
      "../../static/status-icons/25-Divinity.webp": "views/assets/status-icons/25-Divinity.webp",
      "../../static/status-icons/29-HighGuard.webp": "views/assets/status-icons/29-HighGuard.webp",
      "../../static/status-icons/3-Aegis.webp": "views/assets/status-icons/3-Aegis.webp",
      "../../static/status-icons/33-HolyShield.webp": "views/assets/status-icons/33-HolyShield.webp",
      "../../static/status-icons/34-grace.webp": "views/assets/status-icons/34-grace.webp",
      "../../static/status-icons/38-LifeBond.webp": "views/assets/status-icons/38-LifeBond.webp",
      "../../static/status-icons/42-barrier.webp": "views/assets/status-icons/42-barrier.webp",
      "../../static/status-icons/47-EnchantArmorHoly.webp": "views/assets/status-icons/47-EnchantArmorHoly.webp",
      "../../static/status-icons/48-DeathBramble.webp": "views/assets/status-icons/48-DeathBramble.webp",
      "../../static/status-icons/48-Sacrifice.webp": "views/assets/status-icons/48-Sacrifice.webp",
      "../../static/status-icons/49-HolyLight.webp": "views/assets/status-icons/49-HolyLight.webp",
      "../../static/status-icons/49-blessing.webp": "views/assets/status-icons/49-blessing.webp",
      "../../static/status-icons/50-smite.webp": "views/assets/status-icons/50-smite.webp",
      "../../static/status-icons/Barbarian13.webp": "views/assets/status-icons/Barbarian13.webp",
      "../../static/status-icons/Barbarian18.webp": "views/assets/status-icons/Barbarian18.webp",
      "../../static/status-icons/Barbarian20.webp": "views/assets/status-icons/Barbarian20.webp",
      "../../static/status-icons/Berserker11.webp": "views/assets/status-icons/Berserker11.webp",
      "../../static/status-icons/Berserker16.webp": "views/assets/status-icons/Berserker16.webp",
      "../../static/status-icons/Berserker18.webp": "views/assets/status-icons/Berserker18.webp",
      "../../static/status-icons/Berserker8.webp": "views/assets/status-icons/Berserker8.webp",
      "../../static/status-icons/Conditions_0.webp": "views/assets/status-icons/Conditions_0.webp",
      "../../static/status-icons/Conditions_10.webp": "views/assets/status-icons/Conditions_10.webp",
      "../../static/status-icons/Conditions_11.webp": "views/assets/status-icons/Conditions_11.webp",
      "../../static/status-icons/Conditions_12.webp": "views/assets/status-icons/Conditions_12.webp",
      "../../static/status-icons/Conditions_14.webp": "views/assets/status-icons/Conditions_14.webp",
      "../../static/status-icons/Conditions_15.webp": "views/assets/status-icons/Conditions_15.webp",
      "../../static/status-icons/Conditions_17.webp": "views/assets/status-icons/Conditions_17.webp",
      "../../static/status-icons/Conditions_18.webp": "views/assets/status-icons/Conditions_18.webp",
      "../../static/status-icons/Conditions_2.webp": "views/assets/status-icons/Conditions_2.webp",
      "../../static/status-icons/Conditions_20.webp": "views/assets/status-icons/Conditions_20.webp",
      "../../static/status-icons/Conditions_21.webp": "views/assets/status-icons/Conditions_21.webp",
      "../../static/status-icons/Conditions_22.webp": "views/assets/status-icons/Conditions_22.webp",
      "../../static/status-icons/Conditions_23.webp": "views/assets/status-icons/Conditions_23.webp",
      "../../static/status-icons/Conditions_25.webp": "views/assets/status-icons/Conditions_25.webp",
      "../../static/status-icons/Conditions_26.webp": "views/assets/status-icons/Conditions_26.webp",
      "../../static/status-icons/Conditions_27.webp": "views/assets/status-icons/Conditions_27.webp",
      "../../static/status-icons/Conditions_28.webp": "views/assets/status-icons/Conditions_28.webp",
      "../../static/status-icons/Conditions_3.webp": "views/assets/status-icons/Conditions_3.webp",
      "../../static/status-icons/Conditions_31.webp": "views/assets/status-icons/Conditions_31.webp",
      "../../static/status-icons/Conditions_32.webp": "views/assets/status-icons/Conditions_32.webp",
      "../../static/status-icons/Conditions_33.webp": "views/assets/status-icons/Conditions_33.webp",
      "../../static/status-icons/Conditions_35.webp": "views/assets/status-icons/Conditions_35.webp",
      "../../static/status-icons/Conditions_4.webp": "views/assets/status-icons/Conditions_4.webp",
      "../../static/status-icons/Conditions_5.webp": "views/assets/status-icons/Conditions_5.webp",
      "../../static/status-icons/Conditions_7.webp": "views/assets/status-icons/Conditions_7.webp",
      "../../static/status-icons/Conditions_9.webp": "views/assets/status-icons/Conditions_9.webp",
      "../../static/status-icons/Conditions_Immune_10.webp": "views/assets/status-icons/Conditions_Immune_10.webp",
      "../../static/status-icons/Conditions_Immune_12.webp": "views/assets/status-icons/Conditions_Immune_12.webp",
      "../../static/status-icons/Conditions_Immune_20.webp": "views/assets/status-icons/Conditions_Immune_20.webp",
      "../../static/status-icons/Conditions_Immune_26.webp": "views/assets/status-icons/Conditions_Immune_26.webp",
      "../../static/status-icons/Conditions_Immune_31.webp": "views/assets/status-icons/Conditions_Immune_31.webp",
      "../../static/status-icons/Conditions_Immune_33.webp": "views/assets/status-icons/Conditions_Immune_33.webp",
      "../../static/status-icons/Conditions_Immune_5.webp": "views/assets/status-icons/Conditions_Immune_5.webp",
      "../../static/status-icons/Conditions_Immune_9.webp": "views/assets/status-icons/Conditions_Immune_9.webp",
      "../../static/status-icons/Enchanter20.webp": "views/assets/status-icons/Enchanter20.webp",
      "../../static/status-icons/Geomancer5.webp": "views/assets/status-icons/Geomancer5.webp",
      "../../static/status-icons/Necromancer14.webp": "views/assets/status-icons/Necromancer14.webp",
      "../../static/status-icons/Necromancer15.webp": "views/assets/status-icons/Necromancer15.webp",
      "../../static/status-icons/Necromancer3.webp": "views/assets/status-icons/Necromancer3.webp",
      "../../static/status-icons/Priest11.webp": "views/assets/status-icons/Priest11.webp",
      "../../static/status-icons/Priest12.webp": "views/assets/status-icons/Priest12.webp",
      "../../static/status-icons/Pyromancer16.webp": "views/assets/status-icons/Pyromancer16.webp",
      "../../static/status-icons/Skills_052.webp": "views/assets/status-icons/Skills_052.webp",
      "../../static/status-icons/Skills_117.webp": "views/assets/status-icons/Skills_117.webp",
      "../../static/status-icons/Skills_137.webp": "views/assets/status-icons/Skills_137.webp",
      "../../static/status-icons/Skills_247.webp": "views/assets/status-icons/Skills_247.webp",
      "../../static/status-icons/Skills_301.webp": "views/assets/status-icons/Skills_301.webp",
      "../../static/status-icons/Skills_306.webp": "views/assets/status-icons/Skills_306.webp",
      "../../static/status-icons/Skills_307.webp": "views/assets/status-icons/Skills_307.webp",
      "../../static/status-icons/Skills_331.webp": "views/assets/status-icons/Skills_331.webp",
      "../../static/status-icons/Skills_339.webp": "views/assets/status-icons/Skills_339.webp",
      "../../static/status-icons/Skills_355.webp": "views/assets/status-icons/Skills_355.webp",
      "../../static/status-icons/Skills_356.webp": "views/assets/status-icons/Skills_356.webp",
      "../../static/status-icons/Skills_362.webp": "views/assets/status-icons/Skills_362.webp",
      "../../static/status-icons/Skills_366.webp": "views/assets/status-icons/Skills_366.webp",
      "../../static/status-icons/Skills_379.webp": "views/assets/status-icons/Skills_379.webp",
      "../../static/status-icons/Skills_380.webp": "views/assets/status-icons/Skills_380.webp",
      "../../static/status-icons/Skills_397.webp": "views/assets/status-icons/Skills_397.webp",
      "../../static/status-icons/Skills_418.webp": "views/assets/status-icons/Skills_418.webp",
      "../../static/status-icons/Skills_497.webp": "views/assets/status-icons/Skills_497.webp",
      "../../static/status-icons/Skills_499.webp": "views/assets/status-icons/Skills_499.webp",
      "../../static/status-icons/Skills_510.webp": "views/assets/status-icons/Skills_510.webp",
      "../../static/status-icons/Skills_514.webp": "views/assets/status-icons/Skills_514.webp",
      "../../static/status-icons/Skills_515.webp": "views/assets/status-icons/Skills_515.webp",
      "../../static/status-icons/Skills_534.webp": "views/assets/status-icons/Skills_534.webp",
      "../../static/status-icons/Skills_556.webp": "views/assets/status-icons/Skills_556.webp",
      "../../static/status-icons/Skills_565.webp": "views/assets/status-icons/Skills_565.webp",
      "../../static/status-icons/Skills_570.webp": "views/assets/status-icons/Skills_570.webp",
      "../../static/status-icons/Skills_584.webp": "views/assets/status-icons/Skills_584.webp",
      "../../static/status-icons/Skills_593.webp": "views/assets/status-icons/Skills_593.webp",
      "../../static/status-icons/T_Icon_Arcane_21.webp": "views/assets/status-icons/T_Icon_Arcane_21.webp",
      "../../static/status-icons/T_Icon_Arcane_26.webp": "views/assets/status-icons/T_Icon_Arcane_26.webp",
      "../../static/status-icons/T_Icon_Arcane_37.webp": "views/assets/status-icons/T_Icon_Arcane_37.webp",
      "../../static/status-icons/T_Icon_Arcane_63.webp": "views/assets/status-icons/T_Icon_Arcane_63.webp",
      "../../static/status-icons/T_Icon_BloodCombat_04.webp": "views/assets/status-icons/T_Icon_BloodCombat_04.webp",
      "../../static/status-icons/T_Icon_BloodCombat_06.webp": "views/assets/status-icons/T_Icon_BloodCombat_06.webp",
      "../../static/status-icons/T_Icon_BloodCombat_10.webp": "views/assets/status-icons/T_Icon_BloodCombat_10.webp",
      "../../static/status-icons/T_Icon_BloodCombat_11.webp": "views/assets/status-icons/T_Icon_BloodCombat_11.webp",
      "../../static/status-icons/T_Icon_BloodCombat_13.webp": "views/assets/status-icons/T_Icon_BloodCombat_13.webp",
      "../../static/status-icons/T_Icon_BloodCombat_16.webp": "views/assets/status-icons/T_Icon_BloodCombat_16.webp",
      "../../static/status-icons/T_Icon_BloodCombat_31.webp": "views/assets/status-icons/T_Icon_BloodCombat_31.webp",
      "../../static/status-icons/T_Icon_BloodCombat_39.webp": "views/assets/status-icons/T_Icon_BloodCombat_39.webp",
      "../../static/status-icons/T_Icon_BloodCombat_50.webp": "views/assets/status-icons/T_Icon_BloodCombat_50.webp",
      "../../static/status-icons/T_Icon_BloodCombat_89.webp": "views/assets/status-icons/T_Icon_BloodCombat_89.webp",
      "../../static/status-icons/T_Icon_Energy_35.webp": "views/assets/status-icons/T_Icon_Energy_35.webp",
      "../../static/status-icons/T_Icon_Energy_43.webp": "views/assets/status-icons/T_Icon_Energy_43.webp",
      "../../static/status-icons/T_Icon_Energy_55.webp": "views/assets/status-icons/T_Icon_Energy_55.webp",
      "../../static/status-icons/T_Icon_Energy_72.webp": "views/assets/status-icons/T_Icon_Energy_72.webp",
      "../../static/status-icons/T_Icon_Energy_93.webp": "views/assets/status-icons/T_Icon_Energy_93.webp",
      "../../static/status-icons/T_Icon_Fire_104.webp": "views/assets/status-icons/T_Icon_Fire_104.webp",
      "../../static/status-icons/T_Icon_Fire_132.webp": "views/assets/status-icons/T_Icon_Fire_132.webp",
      "../../static/status-icons/T_Icon_Fire_80.webp": "views/assets/status-icons/T_Icon_Fire_80.webp",
      "../../static/status-icons/T_Icon_Frost_03.webp": "views/assets/status-icons/T_Icon_Frost_03.webp",
      "../../static/status-icons/T_Icon_Gold_64.webp": "views/assets/status-icons/T_Icon_Gold_64.webp",
      "../../static/status-icons/T_Icon_Gold_81.webp": "views/assets/status-icons/T_Icon_Gold_81.webp",
      "../../static/status-icons/T_Icon_Gold_89.webp": "views/assets/status-icons/T_Icon_Gold_89.webp",
      "../../static/status-icons/T_Icon_Gold_92.webp": "views/assets/status-icons/T_Icon_Gold_92.webp",
      "../../static/status-icons/T_Icon_Nature_132.webp": "views/assets/status-icons/T_Icon_Nature_132.webp",
      "../../static/status-icons/T_Icon_Nature_70.webp": "views/assets/status-icons/T_Icon_Nature_70.webp",
      "../../static/status-icons/T_Icon_Shadow_04.webp": "views/assets/status-icons/T_Icon_Shadow_04.webp",
      "../../static/status-icons/T_Icon_Shadow_44.webp": "views/assets/status-icons/T_Icon_Shadow_44.webp",
      "../../static/status-icons/T_Icon_Shadow_63.webp": "views/assets/status-icons/T_Icon_Shadow_63.webp",
      "../../static/status-icons/T_Icon_Shadow_77.webp": "views/assets/status-icons/T_Icon_Shadow_77.webp",
      "../../static/status-icons/T_Icon_Shadow_88.webp": "views/assets/status-icons/T_Icon_Shadow_88.webp",
      "../../static/status-icons/T_Icon_Unholy_02.webp": "views/assets/status-icons/T_Icon_Unholy_02.webp",
      "../../static/status-icons/T_Icon_Unholy_04.webp": "views/assets/status-icons/T_Icon_Unholy_04.webp",
      "../../static/status-icons/T_Icon_Unholy_148.webp": "views/assets/status-icons/T_Icon_Unholy_148.webp",
      "../../static/status-icons/T_Icon_Unholy_151.webp": "views/assets/status-icons/T_Icon_Unholy_151.webp",
      "../../static/status-icons/T_Icon_Unholy_63.webp": "views/assets/status-icons/T_Icon_Unholy_63.webp",
      "../../static/status-icons/earth.webp": "views/assets/status-icons/earth.webp",
      "../../static/status-icons/fire.webp": "views/assets/status-icons/fire.webp",
      "../../static/status-icons/holy.webp": "views/assets/status-icons/holy.webp",
      "../../static/status-icons/poison.webp": "views/assets/status-icons/poison.webp",
      "../../static/status-icons/sf_s_074.webp": "views/assets/status-icons/sf_s_074.webp",
      "../../static/status-icons/sf_s_085.webp": "views/assets/status-icons/sf_s_085.webp",
      "../../static/status-icons/sf_s_095.webp": "views/assets/status-icons/sf_s_095.webp",
      "../../static/status-icons/undead.webp": "views/assets/status-icons/undead.webp",
      "../../static/status-icons/water.webp": "views/assets/status-icons/water.webp",
      "../../static/status-icons/wind.webp": "views/assets/status-icons/wind.webp",
      "src/launcherview/index.html": "views/launcherview/index.html",
      "src/launcherview/index.css": "views/launcherview/index.css",
      [themeCssSource(0)]: "views/launcherview/theme.css",
      "src/settingsview/index.html": "views/settingsview/index.html",
      "src/settingsview/index.css": "views/settingsview/index.css",
      [themeCssSource(1)]: "views/settingsview/theme.css",
      "../combat-ui/src/mainview/index.html": "views/mainview/index.html",
      "../combat-ui/src/mainview/index.css": "views/mainview/index.css",
      [themeCssSource(2)]: "views/mainview/theme.css",
      "../overlay/src/overlayview/index.html": "views/overlayview/index.html",
      "../overlay/src/overlayview/index.css": "views/overlayview/index.css",
      [themeCssSource(12)]: "views/overlayview/theme.css",
      "../overlay/src/overlaysettingsview/index.html": "views/overlaysettingsview/index.html",
      "../overlay/src/overlaysettingsview/index.css": "views/overlaysettingsview/index.css",
      [themeCssSource(13)]: "views/overlaysettingsview/theme.css",
      "src/characterview/index.html": "views/characterview/index.html",
      "src/characterview/index.css": "views/characterview/index.css",
      [themeCssSource(4)]: "views/characterview/theme.css",
      "../market-ui/src/marketview/index.html": "views/marketview/index.html",
      "../market-ui/src/marketview/index.css": "views/marketview/index.css",
      [themeCssSource(5)]: "views/marketview/theme.css",
      "../market-ui/src/marketfiltersview/index.html": "views/marketfiltersview/index.html",
      "../market-ui/src/marketfiltersview/index.css": "views/marketfiltersview/index.css",
      [themeCssSource(6)]: "views/marketfiltersview/theme.css",
      "../rewards-ui/src/rewardsview/index.html": "views/rewardsview/index.html",
      "../rewards-ui/src/rewardsview/index.css": "views/rewardsview/index.css",
      [themeCssSource(7)]: "views/rewardsview/theme.css",
      "../rewards-ui/src/catalogview/index.html": "views/rewardscatalogview/index.html",
      "../rewards-ui/src/catalogview/index.css": "views/rewardscatalogview/index.css",
      [themeCssSource(8)]: "views/rewardscatalogview/theme.css",
      "src/sessionpickerview/index.html": "views/sessionpickerview/index.html",
      "src/sessionpickerview/index.css": "views/sessionpickerview/index.css",
      [themeCssSource(9)]: "views/sessionpickerview/theme.css",
      "../combat-ui/src/analysisview/index.html": "views/analysisview/index.html",
      "../combat-ui/src/analysisview/index.css": "views/analysisview/index.css",
      [themeCssSource(10)]: "views/analysisview/theme.css",
      "../combat-ui/src/analysisdetailview/index.html": "views/analysisdetailview/index.html",
      "../combat-ui/src/analysisdetailview/index.css": "views/analysisdetailview/index.css",
      [themeCssSource(11)]: "views/analysisdetailview/theme.css",
    },
    buildFolder: "dist/electrobun",
    artifactFolder: "dist/artifacts",
    targets: "win-x64",
    watch: ["src", "../character/src", "../combat-ui/src", "../capture/src/fishnet", "../items/src", "../market-ui/src", "../overlay/src", "../rewards-ui/src", "../ui-core"],
    win: {
      bundleCEF: false,
      defaultRenderer: "native",
    },
  },
  runtime: {
    exitOnLastWindowClosed: true,
  },
  scripts: {
    postBuild: "../../scripts/embed-electrobun-windows-icon.ts",
    postPackage: "../../scripts/embed-electrobun-windows-installer-icon.ts",
  },
} satisfies ElectrobunConfig;
