export type FishNetMarketSubstatGroup =
  | "Accessory"
  | "Chest"
  | "Feet"
  | "Headgear"
  | "Legs"
  | "Magic"
  | "Melee"
  | "Ranged"
  | "Artifact";

const ITEM_SUBSTAT_GROUPS: Readonly<Record<string, FishNetMarketSubstatGroup>> = {
  "3D Glasses": "Headgear",
  "Abyss Shard": "Melee",
  "Acolyte_1": "Magic",
  "Acolyte_2": "Magic",
  "Acolyte_3": "Magic",
  "Acolyte_4": "Magic",
  "Acolyte_5": "Magic",
  "Acolyte_6": "Magic",
  "Adventurer's Kit": "Headgear",
  "Adventurer's Pack": "Headgear",
  "Amber Bow": "Accessory",
  "Amber Loop": "Accessory",
  "Arcane Sigil": "Headgear",
  "ArcaneChest": "Chest",
  "ArcaneFeet": "Feet",
  "ArcaneGloves": "Accessory",
  "ArcaneLegs": "Legs",
  "Archer's Beads": "Accessory",
  "Armor_Agi": "Chest",
  "Armor_Dex": "Chest",
  "Armor_Int": "Chest",
  "Armor_Luk": "Chest",
  "Armor_Str": "Chest",
  "Armor_Vit": "Chest",
  "Arrow Quiver": "Headgear",
  "Arrowcatch Wall": "Chest",
  "Artemis": "Ranged",
  "Axe": "Melee",
  "Axe of Oblivion": "Melee",
  "Azure Antlers": "Headgear",
  "Azure Crown": "Headgear",
  "Azure Cutlass": "Melee",
  "Azure Prism": "Accessory",
  "Azure Tag": "Accessory",
  "Backpack": "Headgear",
  "Bandit Wrap": "Headgear",
  "Banner Helm": "Headgear",
  "Batling Familiar": "Headgear",
  "Battle Bonnet": "Headgear",
  "Bear Backpack": "Headgear",
  "Bear Hug Hood": "Headgear",
  "Beast Helm": "Headgear",
  "Beast Hood": "Headgear",
  "Beast Pelt Hood": "Headgear",
  "BerserkChest": "Chest",
  "Berserker_1": "Magic",
  "Berserker_2": "Magic",
  "Berserker_3": "Magic",
  "Berserker_4": "Magic",
  "BerserkFeet": "Feet",
  "BerserkLegs": "Legs",
  "Binding Spirits Staff": "Magic",
  "Bishop's Hood": "Headgear",
  "Blacksteel Blade": "Melee",
  "Blade of Eclipse": "Melee",
  "Blade Standard": "Headgear",
  "Blindfold": "Headgear",
  "Blood Clip": "Accessory",
  "Blood Pendant": "Headgear",
  "Bloodbound": "Legs",
  "Bloom of Midnight": "Magic",
  "Bloom Pendant": "Accessory",
  "Bloom Ring": "Accessory",
  "Blue Shell": "Headgear",
  "Blunderbuss": "Ranged",
  "Bomb Bud": "Headgear",
  "Bone Channeler": "Magic",
  "Bone Helm": "Headgear",
  "Bone Pick": "Melee",
  "Bonefang": "Melee",
  "BonkStick": "Melee",
  "Bot Hunter Utility": "Headgear",
  "Breakerhead": "Melee",
  "BreezeguardChest": "Chest",
  "BreezeguardFeet": "Feet",
  "BreezeguardLegs": "Legs",
  "Brimblade": "Melee",
  "Broad Sword": "Melee",
  "Bronze Crescent": "Accessory",
  "Bronze Plugs": "Accessory",
  "Bronze Visage": "Headgear",
  "Bubblebeast Hood": "Headgear",
  "Buckler": "Chest",
  "Bullcrest Helm": "Headgear",
  "Bunny Backpack": "Headgear",
  "Bunny Cap": "Headgear",
  "Caged Spirit": "Headgear",
  "Cardboard Chick": "Headgear",
  "Centurion Helm": "Headgear",
  "Ceremonial Mask": "Headgear",
  "Cerulean Scepter": "Magic",
  "Chainfrost Staff": "Magic",
  "Chains of Binding": "Chest",
  "Champion Blade": "Melee",
  "Chaos Reaver": "Melee",
  "Chicky Hood": "Headgear",
  "Chirpy Hat": "Headgear",
  "Chompy Hood": "Headgear",
  "Chronomancer's Codex": "Headgear",
  "ClericChest": "Chest",
  "ClericFeet": "Feet",
  "ClericLegs": "Legs",
  "Cloud Loop": "Accessory",
  "Codex": "Magic",
  "Codex Binding Light": "Magic",
  "Codex First Hymn": "Magic",
  "Codex of Revelation": "Magic",
  "Codex Umbra": "Magic",
  "Codex Vitae": "Magic",
  "Combat Knife": "Melee",
  "Cotton Mask": "Headgear",
  "Crimson Crest": "Headgear",
  "Crimson Plume": "Headgear",
  "Crown of Spikes": "Headgear",
  "Crusader Staff": "Magic",
  "Crusader Sword": "Melee",
  "Crystal Cache": "Headgear",
  "Crystal Slammer": "Magic",
  "Crystal Wings": "Headgear",
  "Curse Tag": "Headgear",
  "Cursed Grimoire": "Headgear",
  "Daggers": "Headgear",
  "Darkfeather Wings": "Headgear",
  "Darkhide Gloves": "Accessory",
  "Dawn Prayer": "Accessory",
  "Dawnstar": "Magic",
  "Daybreak": "Melee",
  "Death's Grin": "Headgear",
  "Demon Cat": "Headgear",
  "Demon Hood": "Headgear",
  "Destruction Staff": "Magic",
  "Digger's Flask": "Headgear",
  "Dino Cub Backpack": "Headgear",
  "DiscipleArmlets": "Accessory",
  "DiscipleChest": "Chest",
  "DiscipleFeet": "Feet",
  "DiscipleHelm": "Headgear",
  "DiscipleLegs": "Legs",
  "Discipline Band": "Headgear",
  "Doom Crescent": "Melee",
  "Doom Crown": "Headgear",
  "Doom Keg": "Headgear",
  "Double Ravenbeak": "Melee",
  "Dragon Hood": "Headgear",
  "Dragonic Spear": "Melee",
  "Dragonspire Helm": "Headgear",
  "Drooping Angel": "Headgear",
  "Drooping Bat": "Headgear",
  "Drooping Burrow": "Headgear",
  "Drooping Cat": "Headgear",
  "Drooping Dragon": "Headgear",
  "Drooping Flora": "Headgear",
  "Drooping Pup": "Headgear",
  "Drooping Skeleton": "Headgear",
  "Drooping Wraith": "Headgear",
  "Dualblade Sheath": "Headgear",
  "Duskfang": "Melee",
  "Dustweaver Hat": "Headgear",
  "Earth Shaker": "Melee",
  "Earth Shield": "Chest",
  "Eclipse Kunai": "Ranged",
  "Edge of Twilight": "Melee",
  "Elixir Gourd": "Chest",
  "Emberhide Helm": "Headgear",
  "Embershard": "Magic",
  "Emerald Crown": "Headgear",
  "Energy Sword Blue": "Melee",
  "Energy Sword Purple": "Melee",
  "Energy Sword Yellow": "Melee",
  "Everfrost Staff": "Magic",
  "Executioner Axe": "Melee",
  "Exorcist Bible": "Magic",
  "Exorcist Staff": "Magic",
  "Explorer's Pack": "Headgear",
  "Eye of Vigil": "Magic",
  "Eyepatch": "Headgear",
  "Falcon Band": "Headgear",
  "Falcon Hood": "Headgear",
  "Fang Clip": "Accessory",
  "Fang of the Moon": "Melee",
  "Feathered Crown": "Headgear",
  "Feathered Scout Hat": "Headgear",
  "Feet_Agi": "Feet",
  "Feet_Dex": "Feet",
  "Feet_Int": "Feet",
  "Feet_Luk": "Feet",
  "Feet_Str": "Feet",
  "Feet_Vit": "Feet",
  "Ferncloak": "Chest",
  "Festival Cap": "Headgear",
  "Festival Rockets": "Headgear",
  "Festival Turtle Cap": "Headgear",
  "Festive Gift Box": "Headgear",
  "Fire Shield": "Chest",
  "Flame Spirit": "Headgear",
  "Flame Tongue Kunai": "Ranged",
  "Flameburst Kunai": "Ranged",
  "Fleetrunner": "Legs",
  "Flintlock Pistol": "Ranged",
  "Focus Band": "Accessory",
  "Forest Friend Hat": "Headgear",
  "ForestChest": "Chest",
  "ForestFeet": "Feet",
  "ForestLegs": "Legs",
  "Fortified Guardwall": "Chest",
  "Frost Mark": "Ranged",
  "Frostfang": "Melee",
  "Frostscale Helm": "Headgear",
  "Frostshard": "Magic",
  "Frostspire Kunai": "Ranged",
  "Fruit Bowl": "Headgear",
  "Funny Glasses": "Headgear",
  "Fur Hood": "Headgear",
  "Game Master Utility": "Headgear",
  "Gatling Gun": "Ranged",
  "Gentleman's Hat": "Headgear",
  "Ghostly Hat": "Headgear",
  "Glimmerthorn": "Magic",
  "Glove_Agi": "Accessory",
  "Glove_Dex": "Accessory",
  "Glove_Int": "Accessory",
  "Glove_Luk": "Accessory",
  "Glove_Str": "Accessory",
  "Glove_Vit": "Accessory",
  "Golden Aegis": "Chest",
  "Golden Axe": "Melee",
  "Golden Crest": "Headgear",
  "Golden Crown": "Headgear",
  "Golden Hammer": "Magic",
  "Golden Hoop": "Accessory",
  "Grasping Eye Urn": "Headgear",
  "Grave Helm": "Headgear",
  "GravemarrowChest": "Chest",
  "GravemarrowFeet": "Feet",
  "GravemarrowLegs": "Legs",
  "Gravestone Breaker": "Melee",
  "Green Shell": "Headgear",
  "Grim Reaper Scythe": "Melee",
  "Guardblade": "Melee",
  "Happy Chipper Hat": "Headgear",
  "Harlequin's Hood": "Headgear",
  "Harvester of Souls": "Melee",
  "Hawkeye Crossbow": "Ranged",
  "Heart Vessel": "Headgear",
  "Heartgaze Shades": "Headgear",
  "Heartloop Earring": "Accessory",
  "Heaven's Orbit": "Chest",
  "Hellfire Staff": "Magic",
  "Hellhorn Hood": "Headgear",
  "Hermit Hood": "Headgear",
  "Hexweaver Hat": "Headgear",
  "Holy Shield": "Chest",
  "Holy Staff": "Magic",
  "Hornbrand": "Magic",
  "Horned Crusader Helm": "Headgear",
  "Horned Vanguard": "Headgear",
  "Hunter's Hood": "Headgear",
  "Hunter's Roll": "Headgear",
  "Hunting Knife": "Melee",
  "Hunting Pike": "Melee",
  "Insect Carapace": "Headgear",
  "Iron Ankh": "Accessory",
  "Iron Bulwark": "Chest",
  "Iron Fortitude": "Chest",
  "Iron Guard Helm": "Headgear",
  "Iron Halo": "Headgear",
  "Iron Morningstar": "Melee",
  "Iron Reaver": "Melee",
  "Iron Spear": "Melee",
  "Iron Spire": "Headgear",
  "Ironhorn Cap": "Headgear",
  "Ironshade Helm": "Headgear",
  "IslandChest": "Chest",
  "IslandFeet": "Feet",
  "IslandLegs": "Legs",
  "Jagtooth": "Melee",
  "Jester Hat": "Headgear",
  "Jewelcrest Mace": "Magic",
  "Knife": "Melee",
  "Knight_1": "Magic",
  "Knight_2": "Magic",
  "Knight_3": "Magic",
  "Knight_4": "Magic",
  "Knight_5": "Magic",
  "Knight_6": "Magic",
  "Knight's Glory": "Melee",
  "KnightChest": "Chest",
  "KnightFeet": "Feet",
  "KnightLegs": "Legs",
  "Knuckleband": "Accessory",
  "Kunai": "Ranged",
  "Launcher": "Ranged",
  "Leaf Mask": "Headgear",
  "Leg_Agi": "Legs",
  "Leg_Dex": "Legs",
  "Leg_Int": "Legs",
  "Leg_Luk": "Legs",
  "Leg_Str": "Legs",
  "Leg_Vit": "Legs",
  "Legionnaire Helm": "Headgear",
  "Life Staff": "Magic",
  "Lifebloom Shoes": "Feet",
  "Longbow": "Ranged",
  "Lucky Drops": "Accessory",
  "Lute": "Magic",
  "Luxbane": "Melee",
  "Luxspire": "Magic",
  "Mace": "Melee",
  "Mage Guard": "Chest",
  "Mage Plate": "Chest",
  "Mage_1": "Magic",
  "Mage_2": "Magic",
  "Mage_3": "Magic",
  "Mage_4": "Magic",
  "Mage_5": "Magic",
  "Mage_6": "Magic",
  "MageChest": "Chest",
  "MageFeet": "Feet",
  "MageLegs": "Legs",
  "Mana Cask": "Headgear",
  "Mana Potion": "Chest",
  "Master Axe": "Melee",
  "Master Codex": "Magic",
  "Master Dagger": "Melee",
  "Master Hammer": "Magic",
  "Master Katar": "Melee",
  "Master Revolver": "Ranged",
  "Master Scythe": "Melee",
  "Master Slingshot": "Ranged",
  "Master Spear": "Melee",
  "Master Sword": "Melee",
  "Master Wand": "Magic",
  "Mechanical Core": "Headgear",
  "Meteoric Staff": "Magic",
  "Mindweave": "Legs",
  "Mirage Cloak": "Chest",
  "Mischief Gift Box": "Headgear",
  "Mitre of Sanctity": "Headgear",
  "Molten Core": "Headgear",
  "Moonfrost": "Melee",
  "Moonshadow Hat": "Headgear",
  "Moonweave Gloves": "Accessory",
  "Mystic Hat": "Headgear",
  "Mystic Hood": "Headgear",
  "Necronomicon": "Magic",
  "Neko Hood": "Headgear",
  "Night Chest": "Chest",
  "Night Feet": "Feet",
  "Night Helm": "Headgear",
  "Night Legs": "Legs",
  "Night Shield": "Chest",
  "Nightfang Stud": "Accessory",
  "Ninja Hood": "Headgear",
  "Nomad Hood": "Headgear",
  "NoviceChest": "Chest",
  "NoviceFeet": "Feet",
  "NoviceLegs": "Legs",
  "Oak Bow": "Ranged",
  "Oathbound Helm": "Headgear",
  "Obsidian Band": "Accessory",
  "Obsidian Edge": "Melee",
  "Obsidian Loop": "Accessory",
  "Obsidian Pillar": "Headgear",
  "Ocular Grimoire": "Headgear",
  "Onyx Bolt": "Accessory",
  "Ornamented Staff": "Headgear",
  "Oxygen Tank": "Headgear",
  "Paladin Crest": "Headgear",
  "Paladin_1": "Magic",
  "Paladin_2": "Magic",
  "Paladin_3": "Magic",
  "Paladin_4": "Magic",
  "Parrying Knife": "Melee",
  "Phantom Kunai": "Ranged",
  "Phantom Mask": "Headgear",
  "Piercer": "Melee",
  "Pirate Hat": "Headgear",
  "PirateChest": "Chest",
  "PirateFeet": "Feet",
  "PirateGloves": "Accessory",
  "PirateLegs": "Legs",
  "Pistol": "Ranged",
  "Plasma Helmet": "Headgear",
  "Plasma Shell": "Headgear",
  "Plasma Sword Blue": "Melee",
  "Plasma Sword Purple": "Melee",
  "Plasma Sword Yellow": "Melee",
  "PlasmaChest": "Chest",
  "PlasmaFeet": "Feet",
  "PlasmaLegs": "Legs",
  "Plum Talisman": "Accessory",
  "Potion Bowl": "Headgear",
  "Potion Gourd": "Headgear",
  "Potions": "Headgear",
  "Priest_1": "Magic",
  "Priest_2": "Magic",
  "Priest_3": "Magic",
  "Priest_4": "Magic",
  "Priest_5": "Magic",
  "Priest_6": "Magic",
  "Priest_7": "Magic",
  "Priest_8": "Magic",
  "Pumpkin Head": "Headgear",
  "Quillcap": "Headgear",
  "Quiver": "Headgear",
  "Quiver of Thorns": "Headgear",
  "Radiant Dagger": "Melee",
  "Radiant Lyra": "Magic",
  "Radiant Wand": "Magic",
  "Ragebound Fury": "Melee",
  "Raider Helm": "Headgear",
  "Ram Skull Mask": "Headgear",
  "Ransack": "Headgear",
  "Razor Edge": "Melee",
  "Razor Kunai": "Ranged",
  "Reaper Scythe": "Melee",
  "Recurve Bow": "Ranged",
  "Red Maw": "Melee",
  "Red Shell": "Headgear",
  "Regal Tricorne": "Headgear",
  "Reindeer Headband": "Headgear",
  "Reindeer Hood": "Headgear",
  "ReindeerChest": "Chest",
  "ReindeerFeet": "Feet",
  "ReindeerGloves": "Accessory",
  "ReindeerLegs": "Legs",
  "Relic Trident": "Melee",
  "Repeater Crossbow": "Ranged",
  "Resonant Headphones": "Headgear",
  "Rifle": "Ranged",
  "Riftbreaker": "Melee",
  "Rod": "Magic",
  "Rogue_1": "Magic",
  "Rogue_2": "Magic",
  "Rogue_3": "Magic",
  "Rogue_4": "Magic",
  "Rogue_5": "Magic",
  "Round Glasses": "Headgear",
  "Royal Crest": "Chest",
  "Royal Dagger": "Melee",
  "Royal Fang": "Melee",
  "Runeborn Visor": "Headgear",
  "Runecall": "Chest",
  "Runed Staff": "Magic",
  "Runesmasher": "Magic",
  "Runesteel": "Melee",
  "Rusted Binocs": "Headgear",
  "Safety Helmet": "Headgear",
  "SafetyChest": "Chest",
  "SafetyFeet": "Feet",
  "SafetyGloves": "Accessory",
  "SafetyLegs": "Legs",
  "Sailor Cap": "Headgear",
  "SanctifiedChest": "Chest",
  "SanctifiedFeet": "Feet",
  "SanctifiedLegs": "Legs",
  "Sanctum Gloves": "Accessory",
  "Sanctum Guard": "Chest",
  "SantaChest": "Chest",
  "SantaFeet": "Feet",
  "SantaGloves": "Accessory",
  "SantaHat": "Headgear",
  "SantaLegs": "Legs",
  "Sapphire Crown": "Headgear",
  "Sapphire Guard": "Headgear",
  "Satchel of Embers": "Headgear",
  "Scalpel": "Melee",
  "Scholar Glasses": "Headgear",
  "Scholar's Cap": "Headgear",
  "Scout_1": "Magic",
  "Scout_2": "Magic",
  "Scout_3": "Magic",
  "Scout_4": "Magic",
  "Scout_5": "Magic",
  "Scrapfang": "Melee",
  "Scroll Case": "Headgear",
  "Scroll Charm": "Accessory",
  "Scythe": "Melee",
  "Seedling Satchel": "Headgear",
  "Seer's Hood": "Headgear",
  "Serpent Ring": "Headgear",
  "Shadow Dancers": "Feet",
  "Shadow Shield": "Chest",
  "Shady Specs": "Headgear",
  "Sharkbite Hood": "Headgear",
  "Sharpened Visor": "Headgear",
  "Shinobi_1": "Magic",
  "Shinobi_2": "Magic",
  "Shinobi_3": "Magic",
  "Shinobi_4": "Magic",
  "Shotgun": "Ranged",
  "Shuriken": "Ranged",
  "Silence of Night": "Ranged",
  "Skull Emblem": "Headgear",
  "Skull Lord Totem": "Headgear",
  "Skull Pendant": "Accessory",
  "Skullhacker": "Melee",
  "Sky Raider Hat": "Headgear",
  "Skybreaker Staff": "Magic",
  "Skywing Mask": "Headgear",
  "Slingshot": "Ranged",
  "Smith's Tools": "Headgear",
  "Sniper Rifle": "Ranged",
  "Snowbun Earmuffs": "Headgear",
  "Snowman Head": "Headgear",
  "Solar Relic": "Headgear",
  "Solar Spear": "Melee",
  "Solaris Blade": "Melee",
  "Sonic Shoes": "Feet",
  "Soul Reaper Scythe": "Melee",
  "SoulbinderChest": "Chest",
  "SoulbinderFeet": "Feet",
  "SoulbinderLegs": "Legs",
  "Spiked Club": "Melee",
  "Spiked Familiar": "Headgear",
  "Spiked Helm": "Headgear",
  "Spikesteel Helm": "Headgear",
  "Spined Aegis": "Headgear",
  "Spineshard": "Melee",
  "Spirit Familiar": "Chest",
  "Spirit Ward": "Chest",
  "Spooky Spell Hat": "Headgear",
  "Springram Horns": "Headgear",
  "Staff of Eternis": "Magic",
  "Star": "Headgear",
  "Starbound Hat": "Headgear",
  "Starshine Glasses": "Headgear",
  "Stiletto": "Melee",
  "Stonebound Boots": "Feet",
  "Stoneguard": "Chest",
  "Stonepoint Spear": "Melee",
  "Stormburst Crossbow": "Ranged",
  "Stormcall Kunai": "Ranged",
  "Stormcaller Totem": "Headgear",
  "Stormfeather Kunai": "Melee",
  "Stormpiercer": "Ranged",
  "StormplateChest": "Chest",
  "StormplateFeet": "Feet",
  "StormplateLegs": "Legs",
  "Straw Hat": "Headgear",
  "Stylish Shades": "Headgear",
  "Summoner_1": "Magic",
  "Summoner_2": "Magic",
  "Summoner_3": "Magic",
  "Summoner_4": "Magic",
  "Summoner_5": "Magic",
  "Summoner_6": "Magic",
  "Sun Disc": "Headgear",
  "Sun Emblem": "Chest",
  "Sun Emblem Helm": "Headgear",
  "Sun Lion Crest": "Chest",
  "Sunbound Mitts": "Accessory",
  "Suncrest Mace": "Magic",
  "Sunflare": "Melee",
  "Sunflower Clip": "Accessory",
  "Sunglasses": "Headgear",
  "Sunset Shutters": "Headgear",
  "Swampy Hat": "Headgear",
  "Swift Fang": "Melee",
  "Sword": "Melee",
  "Teapot Spirit": "Headgear",
  "Tempest Robes": "Chest",
  "Tempest Staff": "Magic",
  "Thief Mask": "Headgear",
  "ThiefChest": "Chest",
  "ThiefFeet": "Feet",
  "ThiefLegs": "Legs",
  "Thundercoil": "Ranged",
  "Tiger Hat": "Headgear",
  "Tinker Goggles": "Headgear",
  "Tinker Mask": "Headgear",
  "Tinkerer's Tools": "Headgear",
  "Tomahawk": "Melee",
  "Tome of Ages": "Headgear",
  "Top Hat": "Headgear",
  "Totem Banner": "Headgear",
  "Totem Mask": "Headgear",
  "Totem Skull Headdress": "Headgear",
  "Traveler's Trunk": "Headgear",
  "Treasure Box": "Headgear",
  "Treasure Chest": "Headgear",
  "Tribal Mask": "Headgear",
  "Trickster Horns": "Headgear",
  "Trident of Tides": "Melee",
  "Triple Barrel Revolver": "Ranged",
  "TurtleShell": "Headgear",
  "Twinblade": "Melee",
  "Valiant Crown": "Headgear",
  "Valor Helm": "Headgear",
  "Ventilator Mask": "Headgear",
  "Verdant Antlers": "Headgear",
  "Verdant Core": "Magic",
  "Verdant Striders": "Feet",
  "Violet Heart Charm": "Accessory",
  "Void Urn": "Headgear",
  "Voidspike Helm": "Headgear",
  "Voidthreads": "Legs",
  "War Axe": "Melee",
  "War Banner": "Headgear",
  "Warborn Aegis": "Headgear",
  "Warlord Emblem Shield": "Chest",
  "Warrior_1": "Magic",
  "Warrior_2": "Magic",
  "Warrior_3": "Magic",
  "Warrior_4": "Magic",
  "Warrior_5": "Magic",
  "Wasteland Cleaver": "Melee",
  "Water Shield": "Chest",
  "Weaver Gauntlets": "Accessory",
  "Weaver_1": "Magic",
  "Weaver_2": "Magic",
  "Weaver_3": "Magic",
  "Weaver_4": "Magic",
  "Weaver_5": "Magic",
  "WeaverChest": "Chest",
  "WeaverFeet": "Feet",
  "WeaverLegs": "Legs",
  "Whale Backpack": "Headgear",
  "Whisper of Thorns": "Ranged",
  "White Bishop's Hood": "Headgear",
  "Wilderness Pack": "Headgear",
  "Wildroot Veil": "Headgear",
  "Willow Staff": "Magic",
  "Wind Shield": "Chest",
  "Windcarver": "Ranged",
  "Windroot": "Magic",
  "WindstriderChest": "Chest",
  "WindstriderFeet": "Feet",
  "WindstriderLegs": "Legs",
  "Winged Helm": "Headgear",
  "Wings of Valor": "Headgear",
  "Witch's Whisk": "Magic",
  "Witchsteps": "Feet",
  "Wizard_1": "Magic",
  "Wizard_2": "Magic",
  "Wizard_3": "Magic",
  "Wizard_4": "Magic",
  "Wizard_5": "Magic",
  "Wizard_6": "Magic",
  "Wizard_7": "Magic",
  "Wizardry Hat": "Headgear",
  "Wolfcrest Shield": "Headgear",
  "Wooden Guard": "Chest",
  "Worker's Cap": "Headgear",
  "Wraith of Dawn": "Ranged",
  "Wraithlight": "Magic",
  "Zephyrlight": "Magic",
};

export function fishNetMarketSubstatGroup(
  baseItemId: string | undefined,
): FishNetMarketSubstatGroup | undefined {
  return baseItemId === undefined ? undefined : ITEM_SUBSTAT_GROUPS[baseItemId];
}
